<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Market\Controller\ViewController'  => __DIR__ . '/src/Market/Controller/ViewController.php',
    'Market\Controller\IndexController' => __DIR__ . '/src/Market/Controller/IndexController.php',
    'Market\Module'                     => __DIR__ . '/Module.php',
);
